spring:
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mysql://localhost:3306/BMM?createDatabaseIfNotExist=true&connectionTimeZone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 75MB
      max-request-size: 100MB
server:
  port: 8082
dir:
  home: ${user.home}
  images:
    articless: ${user.home}/BM/articles
    personss: ${user.home}/BM/persons
    articles: ${user.dir}/img/articles
    persons: ${user.dir}/img/persons

